// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAgjyXkcrtzX3mnCgGmB1no_kzLuBl0MI',
    appId: '1:721433910152:web:747fa5dd2bcbda9d25383d',
    messagingSenderId: '721433910152',
    projectId: 'campus-bfa74',
    authDomain: 'campus-bfa74.firebaseapp.com',
    storageBucket: 'campus-bfa74.firebasestorage.app',
    measurementId: 'G-E02YY9QTJD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJkgd_UBbgP_l9c_tLfRIjKsz4xYFlo2k',
    appId: '1:721433910152:android:d4af9c6ce5fdb86f25383d',
    messagingSenderId: '721433910152',
    projectId: 'campus-bfa74',
    storageBucket: 'campus-bfa74.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQDf4VsPaGvEgUKpEKJAgr9o9gWYUu8G4',
    appId: '1:721433910152:ios:49db4f11d512ff7f25383d',
    messagingSenderId: '721433910152',
    projectId: 'campus-bfa74',
    storageBucket: 'campus-bfa74.firebasestorage.app',
    iosBundleId: 'com.example.aiCampusAssistant',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQDf4VsPaGvEgUKpEKJAgr9o9gWYUu8G4',
    appId: '1:721433910152:ios:49db4f11d512ff7f25383d',
    messagingSenderId: '721433910152',
    projectId: 'campus-bfa74',
    storageBucket: 'campus-bfa74.firebasestorage.app',
    iosBundleId: 'com.example.aiCampusAssistant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAgjyXkcrtzX3mnCgGmB1no_kzLuBl0MI',
    appId: '1:721433910152:web:c6f039c8ba3ad2d625383d',
    messagingSenderId: '721433910152',
    projectId: 'campus-bfa74',
    authDomain: 'campus-bfa74.firebaseapp.com',
    storageBucket: 'campus-bfa74.firebasestorage.app',
    measurementId: 'G-M3W7CW06SL',
  );
}
