import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:go_router/go_router.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // generated by `flutterfire configure`

import 'services/auth_service.dart';
import 'services/campus_data_service.dart';
import 'config/app_router.dart';
import 'config/theme.dart';
import 'config/constants.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // --- Firebase bootstrap -------------------------------------------------
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);


  final authService = AuthService();
  await authService.restoreSession();

  final campusDataService = CampusDataService();
  // Google Sign-In + Drive load happens here, before the app's home screen
  // shows — see CampusDataService.init() / google_drive_service.dart.
  // This can take a couple seconds on a real device (network + the
  // Google account picker if no session is cached), so it's awaited
  // once at startup rather than blocking every individual screen.
  await campusDataService.init();

  runApp(AiCampusAssistantApp(
    authService: authService,
    campusDataService: campusDataService,
  ));
}

class AiCampusAssistantApp extends StatefulWidget {
  final AuthService authService;
  final CampusDataService campusDataService;
  const AiCampusAssistantApp({
    super.key,
    required this.authService,
    required this.campusDataService,
  });

  @override
  State<AiCampusAssistantApp> createState() => _AiCampusAssistantAppState();
}

class _AiCampusAssistantAppState extends State<AiCampusAssistantApp> {
  late final GoRouter _router;

  @override
  void initState() {
    super.initState();
    _router = buildRouter(widget.authService);
  }

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider<AuthService>.value(value: widget.authService),
        ChangeNotifierProvider<CampusDataService>.value(value: widget.campusDataService),
      ],
      child: Consumer<CampusDataService>(
        builder: (context, campusData, _) {
          return MaterialApp.router(
            title: AppStrings.appName,
            debugShowCheckedModeBanner: false,
            theme: campusData.isDarkMode ? AppTheme.dark() : AppTheme.light(),
            routerConfig: _router,
          );
        },
      ),
    );
  }
}